export const DUMMY_DATA = [
	{
		id: "u1",
		title: "Panadol Extra and the blue one",
		location: "Beirut",
		rating: 4.5,
		type: "Food",
		price: "15",
		username: "Rami",
		imageSrc: require(`../assets/ItemImages/Panadol.png.webp`),
		timePosted: "12 hours ago",
	},
	{
		id: "u2",
		title: "Takis",
		location: "Sidon",
		rating: 1.2,
		type: "Accessories",
		price: "15",
		username: "Chokor",
		imageSrc: require(`../assets/ItemImages/takis.jpeg`),
		timePosted: "12 hours ago",
	},
	{
		id: "u3",
		title: "M1 Macbook air",
		location: "Chouf",
		rating: 4.5,
		type: "Electronics",
		price: "1000",
		username: "Nabil",
		imageSrc: require(`../assets/ItemImages/laptop.jpeg`),
		timePosted: "12 hours ago",
	},
	{
		id: "u4",
		title: "IPhone",
		location: "Beirut",
		rating: 4.5,
		type: "Electronics",
		price: "799",
		username: "Karam",
		imageSrc: require(`../assets/ItemImages/iphone.jpg.webp`),
		timePosted: "12 hours ago",
	},
];

export const DUMMY_DATA_RESIDENT = [
	{
		id: "u1",
		fromLocation: "Dubai",
		toLocation: "Beirut",
		rating: 4.5,
		maxWeight: 15,
		username: "Rami",
		imageSrc: require("../assets/ItemImages/maps.jpg"),
		timePosted: "12 hours ago",
	},
	{
		id: "u2",
		fromLocation: "America",
		toLocation: "Beirut",
		rating: 3.5,
		maxWeight: 15,
		username: "Chokor",
		imageSrc: require("../assets/ItemImages/maps.jpg"),
		timePosted: "12 hours ago",
	},
	{
		id: "u3",
		fromLocation: "Qatar",
		toLocation: "Beirut",
		rating: 5.0,
		maxWeight: 15,
		username: "Nabil",
		imageSrc: require("../assets/ItemImages/maps.jpg"),
		timePosted: "10 hours ago",
	},
	{
		id: "u4",
		fromLocation: "Riyadh",
		toLocation: "Beirut",
		rating: 3.9,
		maxWeight: 29,
		username: "Rami",
		imageSrc: require("../assets/ItemImages/maps.jpg"),
		timePosted: "10 seconds ago",
	},
];
